package testvectors

// Golden vectors for the INSTRUMENT PLANE (QI-M0) — the contract a second,
// independent implementation (the C core on an ESP32) is checked against
// byte for byte. Everything here is derived from fixed seeds; nothing is a
// real identity. Two kinds of entry live side by side:
//
//   - deterministic bytes (ids, payloads, manifest, certificate, a sealed
//     frame with a FIXED nonce, the envelope around it) — regenerated by
//     -update and compared exactly;
//   - one captured-once entry, the epoch wrap, whose HPKE encapsulation is
//     randomized by construction. It is captured on -update and afterwards
//     held as a known-answer test in the OPEN direction: unwrap(enc, ct)
//     must yield the fixed epoch key. That is exactly what a firmware
//     needs to prove — it never wraps, it only unwraps.

import (
	"bytes"
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"

	"golang.org/x/crypto/chacha20poly1305"

	"github.com/drrainlab/quiet_places/kernel/crypto"
	"github.com/drrainlab/quiet_places/kernel/identity"
	"github.com/drrainlab/quiet_places/protocol/codec"
	"github.com/drrainlab/quiet_places/protocol/id"
	"github.com/drrainlab/quiet_places/protocol/manifest"
	"github.com/drrainlab/quiet_places/protocol/schemas"
	"github.com/drrainlab/quiet_places/protocol/signal"
	"github.com/drrainlab/quiet_places/terminals"
	"github.com/drrainlab/quiet_places/terminals/instrument"
)

const instrumentGoldenFile = "instrument_v1.json"

type instrumentVectors struct {
	Note string `json:"note"`

	// Fixed inputs.
	DeviceSeed      string `json:"device_seed"`
	DeviceX25519    string `json:"device_x25519_scalar"`
	TerminalSeed    string `json:"terminal_seed"`
	PrincipalSeed   string `json:"principal_seed"`
	SpaceID         string `json:"space_id"`
	EpochKey        string `json:"epoch_key"`
	EpochN          uint64 `json:"epoch_n"`
	SealNonce       string `json:"seal_nonce"`
	ObservedAt      uint64 `json:"observed_at"`
	CertIssuedAt    uint64 `json:"cert_issued_at"`
	LogicalClock    uint64 `json:"logical_clock"`
	Sequence        uint64 `json:"sequence"`
	PreviousEventID string `json:"previous_event_id"`

	// Derived, deterministic.
	DeviceID        string `json:"device_id"`
	DeviceX25519Pub string `json:"device_x25519_pub"`
	TerminalID      string `json:"terminal_id"`
	PrincipalID     string `json:"principal_id"`
	PlaneID         string `json:"instrument_plane_id"`
	ObservationCBOR string `json:"observation_value_payload"`
	SealAAD         string `json:"seal_aad"`
	SealedPayload   string `json:"sealed_observation_payload"`
	ManifestFrame   string `json:"manifest_frame"`
	ManifestHash    string `json:"manifest_hash"`
	CertFrame       string `json:"certificate_frame"`
	EnvelopeFrame   string `json:"instrument_envelope_frame"`
	EnvelopeID      string `json:"instrument_envelope_event_id"`
	EpochPayloadHdr string `json:"epoch_payload_without_wraps"`

	// Captured once (randomized KEM); verified in the open direction.
	EpochWrapEnc     string `json:"epoch_wrap_enc"`
	EpochWrapCT      string `json:"epoch_wrap_ct"`
	EpochPayloadCBOR string `json:"epoch_payload_cbor"`
}

// greenhouseDecl is the reference panel verbatim (node/instrument.go
// greenhouseChannels) — what a hardware greenhouse must declare.
func greenhouseDecl() []terminals.ChannelDecl {
	return []terminals.ChannelDecl{
		{Channel: "temperature", Kind: "number", Unit: "°C", Label: "Температура"},
		{Channel: "humidity", Kind: "number", Unit: "%", Label: "Влажность"},
		{Channel: "door", Kind: "boolean", Label: "Дверь"},
		{Channel: "light", Kind: "number", Unit: "%", Label: "Свет"},
	}
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func buildInstrumentVectors(t *testing.T) instrumentVectors {
	t.Helper()
	deviceSeed := bytes.Repeat([]byte{0x31}, ed25519.SeedSize)
	var xScalar [32]byte
	for i := range xScalar {
		xScalar[i] = 0x44
	}
	terminalSeed := bytes.Repeat([]byte{0x32}, ed25519.SeedSize)
	principalSeed := bytes.Repeat([]byte{0x33}, ed25519.SeedSize)
	var space id.TerminalID
	for i := range space {
		space[i] = 0x5a
	}
	epochKey := crypto.EpochKey{N: 1}
	for i := range epochKey.Key {
		epochKey.Key[i] = 0x55
	}
	nonce := bytes.Repeat([]byte{0x66}, chacha20poly1305.NonceSizeX)
	const observedAt, issuedAt, clock, seq = uint64(1755800000), uint64(1755790000), uint64(41), uint64(7)
	var prevID id.EventID
	for i := range prevID {
		prevID[i] = 0x77
	}

	dev, err := identity.NewDeviceFromKeys(deviceSeed, xScalar)
	if err != nil {
		t.Fatal(err)
	}
	prin := identity.NewPrincipalFromSeed(principalSeed)
	termPriv := ed25519.NewKeyFromSeed(terminalSeed)
	var term id.TerminalID
	copy(term[:], termPriv.Public().(ed25519.PublicKey))
	plane := terminals.InstrumentPlaneID(space)

	// The manifest: the reference greenhouse declaration, signed by the
	// terminal key, revision 1.
	tmpl, err := instrument.Template("sensor", "Greenhouse", greenhouseDecl())
	if err != nil {
		t.Fatal(err)
	}
	tmpl.Terminal, tmpl.Controller, tmpl.Revision = term, prin.ID, 1
	manFrame, err := tmpl.Sign(termPriv)
	if err != nil {
		t.Fatal(err)
	}

	// The certificate the authority issues for PUBLIC halves only.
	cert := prin.CertifyPublic(dev.ID, dev.X25519Pub, issuedAt, 0)
	certFrame, err := cert.Encode()
	if err != nil {
		t.Fatal(err)
	}

	// One reading, sealed with a FIXED nonce by the documented construction
	// (kernel/crypto.SealPayload draws its nonce at random, so the vector
	// reproduces the construction rather than calling it; OpenPayload is
	// then asked to open the result — the cross-check).
	obs := &schemas.ValueObservation{Channel: "temperature", HasNumber: true,
		Magnitude: 214, Decimals: 1, ObservedAt: observedAt, StaleAfter: 60}
	obsCBOR, err := obs.Encode()
	if err != nil {
		t.Fatal(err)
	}
	aad := append(append(append([]byte{}, plane[:]...), codec.AppendUint(nil, epochKey.N)...),
		[]byte(schemas.ObservationValue)...)
	aead, err := chacha20poly1305.NewX(epochKey.Key[:])
	if err != nil {
		t.Fatal(err)
	}
	ct := aead.Seal(nil, nonce, obsCBOR, aad)
	sealed := codec.AppendMap(nil, 3)
	sealed = codec.AppendUint(sealed, 1)
	sealed = codec.AppendUint(sealed, epochKey.N)
	sealed = codec.AppendUint(sealed, 2)
	sealed = codec.AppendBytes(sealed, nonce)
	sealed = codec.AppendUint(sealed, 3)
	sealed = codec.AppendBytes(sealed, ct)

	// The envelope an instrument emits around it, sequence 7 on its chain.
	src := term
	prev := prevID
	env := &signal.Envelope{
		Terminal: space, Principal: prin.ID, Device: dev.ID,
		Sequence: seq, Previous: &prev,
		Schema: schemas.ObservationValue, CreatedAt: observedAt, LogicalClock: clock,
		ProducedBy: signal.AuthorshipSensor, SourceTerminal: &src,
		PayloadEncoding: signal.PayloadInstrumentSealed, Payload: sealed,
		Priority: signal.PriorityTelemetry, ExpiresAt: observedAt + obs.StaleAfter, MaxForwards: 1,
	}
	frame, err := env.Sign(dev.SignKey())
	if err != nil {
		t.Fatal(err)
	}

	// The epoch payload's deterministic prefix {1: n, 2: array(1)} — the
	// wrap itself is captured separately.
	hdr := codec.AppendMap(nil, 2)
	hdr = codec.AppendUint(hdr, 1)
	hdr = codec.AppendUint(hdr, epochKey.N)
	hdr = codec.AppendUint(hdr, 2)
	hdr = codec.AppendArray(hdr, 1)

	return instrumentVectors{
		Note: "Instrument plane known-answer vectors (QI-M0). Fixed test seeds, never real identities. " +
			"epoch_wrap_* are captured once (HPKE encapsulation is randomized) and verified by unwrapping.",
		DeviceSeed: hex.EncodeToString(deviceSeed), DeviceX25519: hex.EncodeToString(xScalar[:]),
		TerminalSeed: hex.EncodeToString(terminalSeed), PrincipalSeed: hex.EncodeToString(principalSeed),
		SpaceID: space.Hex(), EpochKey: hex.EncodeToString(epochKey.Key[:]), EpochN: epochKey.N,
		SealNonce: hex.EncodeToString(nonce), ObservedAt: observedAt, CertIssuedAt: issuedAt,
		LogicalClock: clock, Sequence: seq, PreviousEventID: prevID.Hex(),
		DeviceID: dev.ID.Hex(), DeviceX25519Pub: hex.EncodeToString(dev.X25519Pub[:]),
		TerminalID: term.Hex(), PrincipalID: prin.ID.Hex(), PlaneID: plane.Hex(),
		ObservationCBOR: hex.EncodeToString(obsCBOR), SealAAD: hex.EncodeToString(aad),
		SealedPayload: hex.EncodeToString(sealed),
		ManifestFrame: hex.EncodeToString(manFrame), ManifestHash: manifest.Hash(manFrame).Hex(),
		CertFrame:     hex.EncodeToString(certFrame),
		EnvelopeFrame: hex.EncodeToString(frame), EnvelopeID: id.EventIDOf(frame).Hex(),
		EpochPayloadHdr: hex.EncodeToString(hdr),
	}
}

func TestInstrumentGoldenVectors(t *testing.T) {
	got := buildInstrumentVectors(t)
	if *update {
		// Capture the randomized wrap once.
		dev, _ := identity.NewDeviceFromKeys(mustHex(t, got.DeviceSeed), [32]byte(mustHex(t, got.DeviceX25519)))
		key := crypto.EpochKey{N: got.EpochN, Key: [32]byte(mustHex(t, got.EpochKey))}
		wraps, err := crypto.WrapEpoch(terminals.InstrumentPlaneID(id.TerminalID(mustHex(t, got.SpaceID))),
			key, map[id.DeviceID][32]byte{dev.ID: dev.X25519Pub})
		if err != nil {
			t.Fatal(err)
		}
		got.EpochWrapEnc, got.EpochWrapCT = hex.EncodeToString(wraps[0].Enc), hex.EncodeToString(wraps[0].CT)
		payload, err := (&schemas.EpochPayload{N: key.N, Wraps: wraps}).Encode()
		if err != nil {
			t.Fatal(err)
		}
		got.EpochPayloadCBOR = hex.EncodeToString(payload)
		data, err := json.MarshalIndent(got, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(instrumentGoldenFile, append(data, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Log("instrument golden vectors updated")
		return
	}
	data, err := os.ReadFile(instrumentGoldenFile)
	if err != nil {
		t.Fatalf("missing golden file (run with -update once): %v", err)
	}
	var want instrumentVectors
	if err := json.Unmarshal(data, &want); err != nil {
		t.Fatal(err)
	}
	// The captured-once entries are not rebuilt; compare the rest exactly.
	got.EpochWrapEnc, got.EpochWrapCT, got.EpochPayloadCBOR = want.EpochWrapEnc, want.EpochWrapCT, want.EpochPayloadCBOR
	if got != want {
		t.Fatalf("instrument vectors drifted — protocol bytes changed.\n got: %+v\nwant: %+v", got, want)
	}
}

// TestInstrumentVectorsOpenIndependently walks the golden file the way a
// firmware would be checked: every captured byte string is consumed by the
// public verification/open path and must yield the fixed inputs.
func TestInstrumentVectorsOpenIndependently(t *testing.T) {
	data, err := os.ReadFile(instrumentGoldenFile)
	if err != nil {
		t.Skip("golden file not generated yet")
	}
	var v instrumentVectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatal(err)
	}
	space := id.TerminalID(mustHex(t, v.SpaceID))
	plane := terminals.InstrumentPlaneID(space)
	if plane.Hex() != v.PlaneID {
		t.Fatal("plane id formula drifted")
	}
	key := crypto.EpochKey{N: v.EpochN, Key: [32]byte(mustHex(t, v.EpochKey))}

	// The fixed-nonce seal opens through the production path.
	pt, err := crypto.OpenPayload(key, plane, schemas.ObservationValue, mustHex(t, v.SealedPayload))
	if err != nil {
		t.Fatalf("production OpenPayload rejects the vector's seal: %v", err)
	}
	if hex.EncodeToString(pt) != v.ObservationCBOR {
		t.Fatal("sealed payload did not open to the observation")
	}
	obs, err := schemas.DecodeValueObservation(pt)
	if err != nil || obs.Magnitude != 214 || obs.Decimals != 1 || obs.Channel != "temperature" {
		t.Fatalf("observation decode: %+v %v", obs, err)
	}

	// The captured wrap unwraps to the fixed key — the firmware's only
	// HPKE direction.
	dev, err := identity.NewDeviceFromKeys(mustHex(t, v.DeviceSeed), [32]byte(mustHex(t, v.DeviceX25519)))
	if err != nil {
		t.Fatal(err)
	}
	ep, err := schemas.DecodeEpochPayload(mustHex(t, v.EpochPayloadCBOR))
	if err != nil {
		t.Fatal(err)
	}
	opened, err := crypto.UnwrapEpoch(plane, ep.N, ep.Wraps, dev.ID, dev.X25519Priv())
	if err != nil {
		t.Fatalf("captured wrap does not unwrap: %v", err)
	}
	if opened.Key != key.Key {
		t.Fatal("unwrapped key differs from the fixed epoch key")
	}
	if hex.EncodeToString(ep.Wraps[0].Enc) != v.EpochWrapEnc || hex.EncodeToString(ep.Wraps[0].CT) != v.EpochWrapCT {
		t.Fatal("epoch payload and wrap fields disagree")
	}
	if !bytes.HasPrefix(mustHex(t, v.EpochPayloadCBOR), mustHex(t, v.EpochPayloadHdr)) {
		t.Fatal("epoch payload prefix drifted")
	}

	// The envelope verifies, names the right device/source, and hashes to
	// the recorded id.
	frame := mustHex(t, v.EnvelopeFrame)
	env, err := signal.Decode(frame)
	if err != nil {
		t.Fatal(err)
	}
	if err := signal.VerifyFrame(frame, env); err != nil {
		t.Fatal(err)
	}
	if id.EventIDOf(frame).Hex() != v.EnvelopeID || env.Device.Hex() != v.DeviceID ||
		env.SourceTerminal == nil || env.SourceTerminal.Hex() != v.TerminalID ||
		env.PayloadEncoding != signal.PayloadInstrumentSealed || env.MaxForwards != 1 ||
		env.Priority != signal.PriorityTelemetry || env.ProducedBy != signal.AuthorshipSensor {
		t.Fatalf("instrument envelope shape drifted: %+v", env)
	}

	// The manifest verifies under the terminal key and declares the panel.
	manFrame := mustHex(t, v.ManifestFrame)
	man, err := manifest.Decode(manFrame)
	if err != nil {
		t.Fatal(err)
	}
	if err := manifest.VerifyFrame(manFrame, man); err != nil {
		t.Fatal(err)
	}
	if man.Terminal.Hex() != v.TerminalID || man.Controller.Hex() != v.PrincipalID {
		t.Fatal("manifest identity drifted")
	}
	decl := terminals.ParseInstruments(man.DeclaredLabels)
	if len(decl) != 4 || decl[1].Unit != "%" || decl[0].Label != "Температура" {
		t.Fatalf("manifest declaration did not round-trip: %+v", decl)
	}

	// The certificate verifies under the principal.
	cert, err := identity.DecodeCertificate(mustHex(t, v.CertFrame))
	if err != nil {
		t.Fatal(err)
	}
	if cert.Device.Hex() != v.DeviceID || cert.Principal.Hex() != v.PrincipalID ||
		hex.EncodeToString(cert.X25519Pub[:]) != v.DeviceX25519Pub {
		t.Fatal("certificate binding drifted")
	}
}
